### ISSUE TITLE
Callback when video has loaded

### ISSUE THREAD

**Issue by cmrn** [henrygd/bigpicture#1]
I'm trying to display my own loading indicator while BigPicture is loading an embedded video. To do this I'd like to be able to define a callback which is called when BigPicture displays the viewer (i.e. the embed has finished loading). This could either be a simple callback or a promise.

Ideally I'd also like an option to disable the built in loading spinner.

**Comment by henrygd** [comment]
Hi Cameron, I've just added options to the script that should allow you to do this. Please take a look at the readme, update to the latest version, and let me know if you run into any trouble.

**Comment by cmrn** [comment]
Brilliant - looks good to me! Thanks @henrygd 🥇
