### ISSUE TITLE
Alert question

### ISSUE THREAD

**Issue by lkoma** [henrygd/bigpicture#15]
If the image does not exist, it will display alert. I hope I can remove the alert. Can I do it?

**Comment by henrygd** [comment]
I'll update this in the near future to give more control over error handling. Having a hard coded English alert is definitely not the best way to go about it.

In the meantime, you can disable the alert by changing the line below. It should say only `return`

https://github.com/henrygd/bigpicture/blob/e1813bee18a7116f75432c47a2971eb5dee0271b/dist/BigPicture.js#L526

Feel free to leave this issue open until I update.

**Comment by lkoma** [comment]
Thank you

**Comment by henrygd** [comment]
Updated with custom error handling. See readme for instructions.


a3568ab6c2839a603e933a23eb8957813575c57a
