### ISSUE TITLE
Transition animation for galleries

### ISSUE THREAD

**Issue by Buzut** [henrygd/bigpicture#16]
Thank you for this awesome lightbox.

Given the attention that has been given to the initial transition, it's almost puzzling to the user that there's no transition between two images of the gallery (like the one in [baguetteBox](https://github.com/feimosi/baguetteBox.js) for instance).

It would be a real plus!

**Comment by henrygd** [comment]
I'll look into it this weekend or the next and try to come up w/ a lightweight animation

**Comment by Buzut** [comment]
Awesome, thank you!

**Comment by henrygd** [comment]
Just to provide an update on this, here's where I'm at: http://obsequious-cloth.surge.sh/

Need to fix captions and maybe add an animation like baguetteBox has if an image is requested out of range. Will be finished sometime this week -- next weekend at the latest.

**Comment by Buzut** [comment]
Awesome!! It's already really nice. Can't wait to see it polished 🥇

**Comment by henrygd** [comment]
Pushed the transition animation 4b41f33465ab5144191b33d2792dcc87c1f42194
