### ISSUE TITLE
open content on click event from js on demand

### ISSUE THREAD

**Issue by ddddddddeee22211** [henrygd/bigpicture#19]
hello
first i want to thank u for the great plugin

I have a need to assign dynamic created divs to preview video and image

and i can create divs as follow

```

<div id="vid1" filesrc="files/vid2.mp4" onclick="previewfile(this); />
<div id="vid2" filesrc="files/vid2.mp4" onclick="previewfile(this); />

<script>
function previewfile(e){
myvidSrc=e.getAttribute('filesrc')
//code to open bigpicture directly without initialization
//.......
}
</script>
```

due to heavy ajax usage I cannot use the initialize constructure on dynamic created div
therefore would it be possible to open the preview from such external function

**Comment by henrygd** [comment]
If I'm understanding you correctly, this should work out of the box. No need for initialization or anything.

I took your code and made a codepen. Let me know if it helps:

https://codepen.io/anon/pen/EdMGJM
