### ISSUE TITLE
Any plans to add support for videos in gallery?

### ISSUE THREAD

**Issue by raRaRa** [henrygd/bigpicture#21]
Hi, are there any plans to add support for videos in gallery? I created a rough solution which seems to work OK, but it doesn't preload videos like it does with images. I basically check if the object in the gallery has .src or .vidSrc to determine if it's video or image.

**Comment by henrygd** [comment]
If you have a fork I'd be happy to take a look at what you've done and tweak it if I can.

As far as implementing in main, for 3.0 I want to allow galleries with mixed content types including youtube / vimeo. That's probably not happening in the very near future, however.

**Comment by henrygd** [comment]
I'll try to take care of it before the end of the month if that works for you.

**Comment by raRaRa** [comment]
That'd be awesome! Thanks!

**Comment by henrygd** [comment]
Didn't have time to refactor to support all media types in galleries, so this isn't an official release, but I did add video gallery support for you here.

Works the same as galleries currently - just change the `data-bp` value to be an mp4, ogg, or webm file. If you want to use multiple sources or need more file formats, let me know. Should be a quick change.

[![Edit bigpicture-vid-gallery](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wo2qnz3zvl)

Minified drop in version if you want it:

```
!function(){var e,r,a,i,p,c,s,l,d,f,u,b,m,g,h,x,y,v,w,_,k,S,E,A,z,M,V,I,O,T,C,D,N=window,L=[],P={},q=document,B="appendChild",G="createElement",R="removeChild",F="innerHTML",H="pointer-events:auto",o="clientHeight",n="clientWidth",X="addEventListener",U=N.setTimeout,W=N.clearTimeout;function Y(){var t=e.getBoundingClientRect();return"transform:translate3D("+(t.left-(a[n]-t.width)/2)+"px, "+(t.top-(a[o]-t.height)/2)+"px, 0) scale3D("+e[n]/i[n]+", "+e[o]/i[o]+", 0)"}function $(t){Array.isArray(t)?(i=c.cloneNode(),t.forEach(function(t){var o=q[G]("SOURCE");o.src=t,o.type="video/"+t.match(/.(\w+)$/)[1],i[B](o)})):(i=c).src=t}function j(n){var t,e=O.length-1;if(!m){if(0<n?I===e&&(t=!0):0===I&&(t=!0),I=Math.max(0,Math.min(I+n,e)),t){if(O[I].error)return;return rt(i,""),void U(rt,9,i,"animation:"+(0<n?"bpl":"bpf")+" .3s;transition:transform .35s")}if([I-1,I,I+1].forEach(function(t){if(t=Math.max(0,Math.min(t,e)),!P[t]){var o,n=O[t].src;if(O[t].isVid)(o=c.cloneNode()).preload=!0,o.src=n;else(o=q[G]("IMG"))[X]("load",tt.bind(null,n)),o.onerror=function(){O[t]={error:"Error loading image"}},o.src=n;P[t]=o}}),P[I].complete)return J(n);if(m=!0,rt(h,"opacity:.4;"),a[B](h),O[I].isVid){!function t(o){~[1,4].indexOf(o.readyState)?(o.complete=!0,k&&J(n)):o.error?(O[I].error="Error loading video",o.complete=!0,k&&J(n)):U(t,35,o)}(P[I])}else P[I].onload=function(){k&&J(n)}}}function J(t){m&&(a[R](h),m=!1);var o=O[I];o.error&&alert(o.error);var n=o.isVid;if(n&&c.pause(),rt(i,"animation:"+(0<t?"bpfol":"bpfor")+" .35s both"),!o.error){n?c=i=P[I]:p=i=P[I],rt(i,"animation:"+(0<t?"bpfl":"bpfr")+" .35s;transition:transform .35s"),a[B](i),n&&i.play(),o.el&&(e=o.el)}T[F]=I+1+"/"+O.length,Z(O[I].caption)}function K(t){~[1,4].indexOf(i.readyState)?(ot(),U(function(){i.play()},99)):i.error?ot(t):g=U(K,35,t)}function Q(t){D.noLoader||(t&&rt(h,"top:"+e.offsetTop+"px;left:"+e.offsetLeft+"px;height:"+e[o]+"px;width:"+e[n]+"px"),e.parentElement[t?B:R](h),m=t)}function Z(t){t&&(y[F]=t),rt(x,"opacity:"+(t?"1;"+H:"0"))}function tt(t){!~L.indexOf(t)&&L.push(t)}function ot(t){if(m&&Q(),A&&A(),"string"==typeof t)return et(),D.onError?D.onError():alert("Error: The requested "+t+" could not be loaded.");E&&tt(f),rt(i,Y()),rt(a,"opacity:1;"+H),z=U(z,410),_=!0,k=!!O,U(function(){rt(i,"transition:transform .35s;transform:none"),v&&U(Z,250,v)},60)}function nt(t){var o=t.target,n=[x,w,c,s,y,V,M,h];o&&o.blur(),S||~n.indexOf(o)||(i.style.cssText+=Y(),rt(a,H),U(et,350),W(z),S=!(_=!1))}function et(){if(q.body[R](a),a[R](i),rt(a,""),(i===l?d:i).removeAttribute("src"),Z(!1),k){for(var t=a.querySelectorAll("img, video"),o=0;o<t.length;o++)a[R](t[o]);m&&a[R](h),a[R](T),k=O=!1,P={},C||a[R](M),C||a[R](V),p.onload=ot,p.onerror=ot.bind(null,"image")}D.onClose&&D.onClose(),S=m=!1}function rt(t,o){t.style.cssText=o}N.BigPicture=function(t){var o,n;r||function(){var e;function t(){var t=q[G]("button");return t.className="bp-x",t[F]="&#215;",t}function o(o,t){var n=q[G]("button");return n.className="bp-lr",n[F]='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 129 129" height="75" fill="#fff"><path d="M88.6 121.3c.8.8 1.8 1.2 2.9 1.2s2.1-.4 2.9-1.2a4.1 4.1 0 0 0 0-5.8l-51-51 51-51a4.1 4.1 0 0 0-5.8-5.8l-54 53.9a4.1 4.1 0 0 0 0 5.8l54 53.9z"/></svg>',rt(n,t),n.onclick=function(t){t.stopPropagation(),j(o)},n}var n=q[G]("STYLE");n[F]=".bp-lr,.bp-x:active{outline:0}#bp_caption,#bp_container{bottom:0;left:0;right:0;position:fixed;opacity:0}#bp_container>*,#bp_loader,.bp-x{position:absolute;right:0;z-index:10}#bp_container{top:0;z-index:9999;background:rgba(0,0,0,.7);opacity:0;pointer-events:none;transition:opacity .35s}#bp_loader{top:0;left:0;bottom:0;display:flex;margin:0;cursor:wait;z-index:9;background:transparent}#bp_count,.bp-lr,.bp-x{cursor:pointer;color:#fff}#bp_loader svg{width:50%;max-width:300px;max-height:50%;margin:auto;animation:bpturn 1s infinite linear}#bp_container img,#bp_sv,#bp_aud,#bp_vid{user-select:none;max-height:96%;max-width:96%;top:0;bottom:0;left:0;margin:auto;box-shadow:0 0 3em rgba(0,0,0,.4);z-index:-1}#bp_sv{height:0;padding-bottom:54%;background-color:#000;width:96%}@media (min-aspect-ratio:9/5){#bp_sv{height:98%;width:170.6vh;padding:0}}#bp_caption{pointer-events:none;font-size:.9em;padding:1.3em;background:rgba(15,15,15,.94);color:#fff;text-align:center;transition:opacity .3s}#bp_count,.bp-x{top:0;opacity:.8;font-size:3em;padding:0 .3em;background:0 0;border:0;text-shadow:0 0 2px rgba(0,0,0,.6)}#bp_caption .bp-x{left:2%;top:auto;right:auto;bottom:100%;padding:0 .6em;background:#d74040;border-radius:2px 2px 0 0;font-size:2.3em;text-shadow:none}.bp-x:focus,.bp-x:hover{opacity:1}#bp_aud{width:650px;top:calc(50% - 20px);bottom:auto;box-shadow:none}.bp-lr{top:50%;top:calc(50% - 138px);padding:99px 0;width:6%;background:0 0;border:0;opacity:.4;transition:opacity .1s}.bp-lr:focus,.bp-lr:hover{opacity:.8}@media (max-width:600px){.bp-lr{font-size:15vw}}#bp_count{left:0;display:table;padding:14px;color:#fff;font-size:22px;opacity:.7;cursor:default;right:auto}@keyframes bpf{50%{transform:translatex(15px)}100%{transform:none}}@keyframes bpl{50%{transform:translatex(-15px)}100%{transform:none}}@keyframes bpfl{0%{opacity:0;transform:translatex(70px)}100%{opacity:1;transform:none}}@keyframes bpfr{0%{opacity:0;transform:translatex(-70px)}100%{opacity:1;transform:none}}@keyframes bpfol{0%{opacity:1;transform:none}100%{opacity:0;transform:translatex(-70px)}}@keyframes bpfor{0%{opacity:1;transform:none}100%{opacity:0;transform:translatex(70px)}}@keyframes bpturn{0%{transform:none}100%{transform:rotate(360deg)}}",q.head[B](n),(a=q[G]("DIV")).id="bp_container",a.onclick=nt,u=t(),a[B](u),"ontouchstart"in N&&(C=!0,a.ontouchstart=function(t){e=t.changedTouches[0].pageX},a.ontouchmove=function(t){t.preventDefault()},a.ontouchend=function(t){if(k){var o=t.changedTouches[0],n=o.pageX-e;n<-30&&j(1),30<n&&j(-1)}});p=q[G]("IMG"),(c=q[G]("VIDEO")).id="bp_vid",c.setAttribute("playsinline",!0),c.controls=!0,c.loop=!0,(s=q[G]("audio")).id="bp_aud",s.controls=!0,s.loop=!0,(T=q[G]("span")).id="bp_count",(x=q[G]("DIV")).id="bp_caption",(w=t()).onclick=Z.bind(null,!1),x[B](w),y=q[G]("SPAN"),x[B](y),a[B](x),M=o(1,"transform:scalex(-1)"),V=o(-1,"left:0;right:auto"),(h=q[G]("DIV")).id="bp_loader",h[F]='<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 32 32" fill="#fff" opacity=".8"><path d="M16 0a16 16 0 0 0 0 32 16 16 0 0 0 0-32m0 4a12 12 0 0 1 0 24 12 12 0 0 1 0-24" fill="#000" opacity=".5"/><path d="M16 0a16 16 0 0 1 16 16h-4A12 12 0 0 0 16 4z"/></svg>',(l=q[G]("DIV")).id="bp_sv",(d=q[G]("IFRAME")).allowFullscreen=!0,d.onload=ot,rt(d,"border:0;position:absolute;height:100%;width:100%;left:0;top:0"),l[B](d),p.onload=ot,p.onerror=ot.bind(null,"image"),N[X]("resize",function(){k||m&&Q(!0)}),q[X]("keyup",function(t){var o=t.keyCode;27===o&&_&&nt(a),k&&(39===o&&j(1),37===o&&j(-1),38===o&&j(10),40===o&&j(-10))}),q[X]("keydown",function(t){k&&~[37,38,39,40].indexOf(t.keyCode)&&t.preventDefault()}),q[X]("focus",function(t){_&&!a.contains(t.target)&&(t.stopPropagation(),u.focus())},!0),r=!0}(),m&&(W(g),et()),b=(D=t).ytSrc||t.vimeoSrc,A=t.animationStart,z=t.animationEnd,e=t.el,E=!1,v=e.getAttribute("data-caption"),t.gallery?function(t){if(Array.isArray(t))v=(O=t)[I=0].caption;else{var o=(O=[].slice.call("string"==typeof t?q.querySelectorAll(t+" [data-bp]"):t)).indexOf(e);I=-1!==o?o:0,O=O.map(function(t){var o=t.getAttribute("data-bp");return{el:t,src:o,caption:t.getAttribute("data-caption"),isVid:/\.(mp4|webm|ogg)/i.test(o)}})}E=!O[I].isVid,f=O[I].src,!~L.indexOf(f)&&Q(!0),1<O.length?(a[B](T),T[F]=I+1+"/"+O.length,C||(a[B](M),a[B](V))):O=!1;O[I].isVid?($(f),K("video")):(i=p).src=f}(t.gallery):b?(Q(!0),i=l,o=!!t.ytSrc,n=o?"www.youtube.com/embed/"+b+"?html5=1&rel=0&playsinline=1&":"player.vimeo.com/video/"+b+"?",d.src="https://"+n+"autoplay=1"):t.imgSrc?(E=!0,f=t.imgSrc,!~L.indexOf(f)&&Q(!0),(i=p).src=f):t.audio?(Q(!0),(i=s).src=t.audio,K("audio file")):t.vidSrc?(Q(!0),$(t.vidSrc),K("video")):(i=p).src="IMG"===e.tagName?e.src:N.getComputedStyle(e).backgroundImage.replace(/^url|[(|)|'|"]/g,""),a[B](i),q.body[B](a)}}();
```

**Comment by henrygd** [comment]
For sure, that'd be good. Make a pull request whenever you have time and I'll merge.

Also, forgot to add that if you're making the gallery from an array, add `isVid: true` to the videos. For example:

```javascript
gallery: [
  {
    src: 'vid.mp4',
    isVid: true
  },
  {
    src: 'pic.jpg'
  }
]
```

**Comment by eliavmaman** [comment]
fixed that issue by adding that under row row 376
```
galleryPosition = parseInt(el.querySelector('[data-bp]').getAttribute('data-bp-pos'));
```
and add attribute to item "data-bp-pos"

**Comment by evrenbal** [comment]
> Didn't have time to refactor to support all media types in galleries, so this isn't an official release, but I did add video gallery support for you here.
> 
> Works the same as galleries currently - just change the `data-bp` value to be an mp4, ogg, or webm file. If you want to use multiple sources or need more file formats, let me know. Should be a quick change.
> 
> [![Edit bigpicture-vid-gallery](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/wo2qnz3zvl)
> 
> Minified drop in version if you want it:
> 
> ```
> !function(){var e,r,a,i,p,c,s,l,d,f,u,b,m,g,h,x,y,v,w,_,k,S,E,A,z,M,T,V,I,O,C,D,N=window,L=[],P={},q=document,B="appendChild",G="createElement",R="removeChild",F="innerHTML",H="pointer-events:auto",o="clientHeight",n="clientWidth",X="addEventListener",U=N.setTimeout,W=N.clearTimeout;function Y(){var t=e.getBoundingClientRect();return"transform:translate3D("+(t.left-(a[n]-t.width)/2)+"px, "+(t.top-(a[o]-t.height)/2)+"px, 0) scale3D("+e[n]/i[n]+", "+e[o]/i[o]+", 0)"}function $(t){Array.isArray(t)?(i=c.cloneNode(),t.forEach(function(t){var o=q[G]("SOURCE");o.src=t,o.type="video/"+t.match(/.(\w+)$/)[1],i[B](o)})):(i=c).src=t}function j(n){var t,e=I.length-1;if(!m){if(0<n?V===e&&(t=!0):0===V&&(t=!0),V=Math.max(0,Math.min(V+n,e)),t){if(I[V].error)return;return rt(i,""),void U(rt,9,i,"animation:"+(0<n?"bpl":"bpf")+" .3s;transition:transform .35s")}if([V-1,V,V+1].forEach(function(t){if(t=Math.max(0,Math.min(t,e)),!P[t]){var o,n=I[t].src;I[t].isVid?((o=c.cloneNode()).pause(),o.preload=!0):((o=q[G]("IMG"))[X]("load",tt.bind(null,n)),o.onerror=function(){I[t]={error:"Error loading image"}}),o.src=n,P[t]=o}}),P[V].complete)return J(n);if(m=!0,rt(h,"opacity:.4;"),a[B](h),I[V].isVid){!function t(o){~[1,4].indexOf(o.readyState)?(o.complete=!0,o.currentTime=0,k&&J(n)):o.error?(I[V].error="Error loading video",o.complete=!0,k&&J(n)):U(t,35,o)}(P[V])}else P[V].onload=function(){k&&J(n)}}}function J(t){m&&(a[R](h),m=!1);var o=I[V];o.error&&alert(o.error);var n=o.isVid;i===c&&c.pause(),rt(i,"animation:"+(0<t?"bpfol":"bpfor")+" .35s both"),o.error||(n?c=i=P[V]:p=i=P[V],rt(i,"animation:"+(0<t?"bpfl":"bpfr")+" .35s;transition:transform .35s"),a[B](i),n&&i.play(),o.el&&(e=o.el)),O[F]=V+1+"/"+I.length,Z(I[V].caption)}function K(t){~[1,4].indexOf(i.readyState)?(ot(),U(function(){i.play()},99)):i.error?ot(t):g=U(K,35,t)}function Q(t){D.noLoader||(t&&rt(h,"top:"+e.offsetTop+"px;left:"+e.offsetLeft+"px;height:"+e[o]+"px;width:"+e[n]+"px"),e.parentElement[t?B:R](h),m=t)}function Z(t){t&&(y[F]=t),rt(x,"opacity:"+(t?"1;"+H:"0"))}function tt(t){!~L.indexOf(t)&&L.push(t)}function ot(t){if(m&&Q(),A&&A(),"string"==typeof t)return et(),D.onError?D.onError():alert("Error: The requested "+t+" could not be loaded.");E&&tt(f),rt(i,Y()),rt(a,"opacity:1;"+H),z=U(z,410),_=!0,k=!!I,U(function(){rt(i,"transition:transform .35s;transform:none"),v&&U(Z,250,v)},60)}function nt(t){var o=t.target,n=[x,w,c,s,y,T,M,h];o&&o.blur(),S||~n.indexOf(o)||(i.style.cssText+=Y(),rt(a,H),U(et,350),W(z),S=!(_=!1))}function et(){if(q.body[R](a),a[R](i),rt(a,""),(i===l?d:i).removeAttribute("src"),Z(!1),k){for(var t=a.querySelectorAll("img, video"),o=0;o<t.length;o++)a[R](t[o]);m&&a[R](h),a[R](O),k=I=!1,P={},C||a[R](M),C||a[R](T),p.onload=ot,p.onerror=ot.bind(null,"image")}D.onClose&&D.onClose(),S=m=!1}function rt(t,o){t.style.cssText=o}N.BigPicture=function(t){var o,n;r||function(){var e;function t(){var t=q[G]("button");return t.className="bp-x",t[F]="&#215;",t}function o(o,t){var n=q[G]("button");return n.className="bp-lr",n[F]='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 129 129" height="75" fill="#fff"><path d="M88.6 121.3c.8.8 1.8 1.2 2.9 1.2s2.1-.4 2.9-1.2a4.1 4.1 0 0 0 0-5.8l-51-51 51-51a4.1 4.1 0 0 0-5.8-5.8l-54 53.9a4.1 4.1 0 0 0 0 5.8l54 53.9z"/></svg>',rt(n,t),n.onclick=function(t){t.stopPropagation(),j(o)},n}var n=q[G]("STYLE");n[F]=".bp-lr,.bp-x:active{outline:0}#bp_caption,#bp_container{bottom:0;left:0;right:0;position:fixed;opacity:0}#bp_container>*,#bp_loader,.bp-x{position:absolute;right:0;z-index:10}#bp_container{top:0;z-index:9999;background:rgba(0,0,0,.7);opacity:0;pointer-events:none;transition:opacity .35s}#bp_loader{top:0;left:0;bottom:0;display:flex;margin:0;cursor:wait;z-index:9;background:transparent}#bp_count,.bp-lr,.bp-x{cursor:pointer;color:#fff}#bp_loader svg{width:50%;max-width:300px;max-height:50%;margin:auto;animation:bpturn 1s infinite linear}#bp_container img,#bp_sv,#bp_aud,#bp_vid{user-select:none;max-height:96%;max-width:96%;top:0;bottom:0;left:0;margin:auto;box-shadow:0 0 3em rgba(0,0,0,.4);z-index:-1}#bp_sv{height:0;padding-bottom:54%;background-color:#000;width:96%}@media (min-aspect-ratio:9/5){#bp_sv{height:98%;width:170.6vh;padding:0}}#bp_caption{pointer-events:none;font-size:.9em;padding:1.3em;background:rgba(15,15,15,.94);color:#fff;text-align:center;transition:opacity .3s}#bp_count,.bp-x{top:0;opacity:.8;font-size:3em;padding:0 .3em;background:0 0;border:0;text-shadow:0 0 2px rgba(0,0,0,.6)}#bp_caption .bp-x{left:2%;top:auto;right:auto;bottom:100%;padding:0 .6em;background:#d74040;border-radius:2px 2px 0 0;font-size:2.3em;text-shadow:none}.bp-x:focus,.bp-x:hover{opacity:1}#bp_aud{width:650px;top:calc(50% - 20px);bottom:auto;box-shadow:none}.bp-lr{top:50%;top:calc(50% - 138px);padding:99px 0;width:6%;background:0 0;border:0;opacity:.4;transition:opacity .1s}.bp-lr:focus,.bp-lr:hover{opacity:.8}@media (max-width:600px){.bp-lr{font-size:15vw}}#bp_count{left:0;display:table;padding:14px;color:#fff;font-size:22px;opacity:.7;cursor:default;right:auto}@keyframes bpf{50%{transform:translatex(15px)}100%{transform:none}}@keyframes bpl{50%{transform:translatex(-15px)}100%{transform:none}}@keyframes bpfl{0%{opacity:0;transform:translatex(70px)}100%{opacity:1;transform:none}}@keyframes bpfr{0%{opacity:0;transform:translatex(-70px)}100%{opacity:1;transform:none}}@keyframes bpfol{0%{opacity:1;transform:none}100%{opacity:0;transform:translatex(-70px)}}@keyframes bpfor{0%{opacity:1;transform:none}100%{opacity:0;transform:translatex(70px)}}@keyframes bpturn{0%{transform:none}100%{transform:rotate(360deg)}}",q.head[B](n),(a=q[G]("DIV")).id="bp_container",a.onclick=nt,u=t(),a[B](u),"ontouchstart"in N&&(C=!0,a.ontouchstart=function(t){e=t.changedTouches[0].pageX},a.ontouchmove=function(t){t.preventDefault()},a.ontouchend=function(t){if(k){var o=t.changedTouches[0],n=o.pageX-e;n<-30&&j(1),30<n&&j(-1)}});p=q[G]("IMG"),(c=q[G]("VIDEO")).id="bp_vid",c.setAttribute("playsinline",!0),c.controls=!0,c.loop=!0,(s=q[G]("audio")).id="bp_aud",s.controls=!0,s.loop=!0,(O=q[G]("span")).id="bp_count",(x=q[G]("DIV")).id="bp_caption",(w=t()).onclick=Z.bind(null,!1),x[B](w),y=q[G]("SPAN"),x[B](y),a[B](x),M=o(1,"transform:scalex(-1)"),T=o(-1,"left:0;right:auto"),(h=q[G]("DIV")).id="bp_loader",h[F]='<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 32 32" fill="#fff" opacity=".8"><path d="M16 0a16 16 0 0 0 0 32 16 16 0 0 0 0-32m0 4a12 12 0 0 1 0 24 12 12 0 0 1 0-24" fill="#000" opacity=".5"/><path d="M16 0a16 16 0 0 1 16 16h-4A12 12 0 0 0 16 4z"/></svg>',(l=q[G]("DIV")).id="bp_sv",(d=q[G]("IFRAME")).allowFullscreen=!0,d.onload=ot,rt(d,"border:0;position:absolute;height:100%;width:100%;left:0;top:0"),l[B](d),p.onload=ot,p.onerror=ot.bind(null,"image"),N[X]("resize",function(){k||m&&Q(!0)}),q[X]("keyup",function(t){var o=t.keyCode;27===o&&_&&nt(a),k&&(39===o&&j(1),37===o&&j(-1),38===o&&j(10),40===o&&j(-10))}),q[X]("keydown",function(t){k&&~[37,38,39,40].indexOf(t.keyCode)&&t.preventDefault()}),q[X]("focus",function(t){_&&!a.contains(t.target)&&(t.stopPropagation(),u.focus())},!0),r=!0}(),m&&(W(g),et()),b=(D=t).ytSrc||t.vimeoSrc,A=t.animationStart,z=t.animationEnd,e=t.el,E=!1,v=e.getAttribute("data-caption"),t.gallery?function(t){if(Array.isArray(t))v=(I=t)[V=0].caption;else{var o=(I=[].slice.call("string"==typeof t?q.querySelectorAll(t+" [data-bp]"):t)).indexOf(e);V=-1!==o?o:0,I=I.map(function(t){var o=t.getAttribute("data-bp");return{el:t,src:o,caption:t.getAttribute("data-caption"),isVid:/\.(mp4|webm|ogg)/i.test(o)}})}E=!I[V].isVid,f=I[V].src,!~L.indexOf(f)&&Q(!0),1<I.length?(a[B](O),O[F]=V+1+"/"+I.length,C||(a[B](M),a[B](T))):I=!1;I[V].isVid?($(f),K("video")):(i=p).src=f}(t.gallery):b?(Q(!0),i=l,o=!!t.ytSrc,n=o?"www.youtube.com/embed/"+b+"?html5=1&rel=0&playsinline=1&":"player.vimeo.com/video/"+b+"?",d.src="https://"+n+"autoplay=1"):t.imgSrc?(E=!0,f=t.imgSrc,!~L.indexOf(f)&&Q(!0),(i=p).src=f):t.audio?(Q(!0),(i=s).src=t.audio,K("audio file")):t.vidSrc?(Q(!0),$(t.vidSrc),K("video")):(i=p).src="IMG"===e.tagName?e.src:N.getComputedStyle(e).backgroundImage.replace(/^url|[(|)|'|"]/g,""),a[B](i),q.body[B](a)}}();
> ```
> 
> edit: fixed IE pause / seek issue

It seems like the change you made is working for native videos but not for YouTube or Vimeo. Is there a planned time for the 3.0 version you mentioned earlier above that will also support these?

**Comment by henrygd** [comment]
@eliavmaman I made a new library instead of doing 3.0 because I wanted to leave this one as minimal as possible. It should do everything you need.

https://github.com/henrygd/bigger-picture
