### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by T7team** [henrygd/bigpicture#26]
Hi, how can I do loop for gallery? 
Thanks for nice script :)

**Comment by henrygd** [comment]
Hi Anatoliy, just want to make sure I understand.

By loop, do you mean clicking next on the last picture gives you the first picture?

**Comment by T7team** [comment]
Yes, I mean it.

**Comment by henrygd** [comment]
Updated to 2.1.3 which includes this feature.

**Comment by T7team** [comment]
Thank you very much.
