### ISSUE TITLE
When initiating with Array, can't pass initial position other than 0

### ISSUE THREAD

**Issue by adamkiss** [henrygd/bigpicture#27]
If, for whatever reasons[1], you try to initiate the gallery with `Array` of elements, [this line of `makeGallery`](https://github.com/henrygd/bigpicture/blob/5a2a3d4cb883ceb4cdc3f5f72b09a1aebc69be40/index.js#L352) automatically sets the position to `0`, and there's no way to set it to any other position. I'd like to propose (I'll PR this, even) to add an optional `position` argument, which would apply here.

So you could do this:

``` javascript
BigPicture({
  el: this,
  position: someValueIGot,
  gallery: galleryElements
})
```

This would be useful in use cases where you get the elements/nodes in other way than from DOM.

Also, thank you for making this :tada:.

[1]: In my case, I've tried to pair this with [Stimulus by Basecamp](https://stimulusjs.org/), which _probably_ returns an `array of Nodes` instead of `NodeList`. When I've modified it transform the elements to `array` for BigPicture , I was still not able to force the gallery position.

**Comment by henrygd** [comment]
Hi Adam,

I agree this should be an option. Not sure why I did it that way.

Will definitely merge if you want to make a pull request -- otherwise I should be able to add it in this weekend :+1:

**Comment by henrygd** [comment]
Merged pull request https://github.com/henrygd/bigpicture/pull/28

**Comment by adamkiss** [comment]
🎉 

Just for a bit of feedback, I've noticed the simplification to `position || 0` and such — I used the more complicated version for cases if you for instance had a HTML like: 
```
<div>
  <h2>Whatever</h2>
  <a>Link (position: 0, but gets overwritten by indexEl: 1)
</div>
```

That was probably overly complicated, is that right?

**Comment by adamkiss** [comment]
(specifically the second part of `makeGallery` — I just realized that the `array` part would come out to `0 || 0` anyway)

**Comment by henrygd** [comment]
Ah, you're totally right. I was trying to save a few bytes didn't catch that a positive element index would take if someone was trying to pass in position 0 for a non-array. 

I'm going to restore your line to how it was. Sorry about that! :man_facepalming:
