### ISSUE TITLE
Aspect Ratio seems not working correnctly with iframe. Black bars in Vimeo video.

### ISSUE THREAD

**Issue by nextgenthemes** [henrygd/bigpicture#30]
See: https://codepen.io/nnico/pen/OJJRzyL

I am trying to use it for a Vimeo Video with a very wide Aspect Ratio and it creates black bars.

I saw in the source that you at some point take the dimensions of the element specified and that you set the css to `positon: absolute;` but I could not figure out how the aspect ratio it kept. No `position: relative` ?

I would rather like to just pass a string of HTML to be used for wrappers I have prepared with the `padding-top` element as sibling where the + `position: absolute` `iframe` is.

**Comment by nextgenthemes** [comment]
Thank I am looking forward to this.

 Just so you know, in case flexbox comes into play at some point. I have seen Bootstrap moving from putting a `padding-bottom: xx%` on the wrapper to using a `::before` pseudo element and putting a `padding-top: xx%` on that. https://github.com/twbs/bootstrap/blob/master/scss/helpers/_embed.scss

There was the change https://github.com/twbs/bootstrap/pull/19739/files

AMP does it this way too. They not use a pseudo but a div where the put `padding-top: xx%` on as the first element of in the wrapper. Its probably a better technique to use nowadays.

I would also create a additional wrapper for the responsiveness. Like inside the `#bp_sv` I have seen things get messy with max-width and this responsiveness hacks b4.

**Comment by henrygd** [comment]
Added in 2.3.0

https://codepen.io/henrygd/pen/vYYyZZW

https://github.com/henrygd/bigpicture#change-dimensions-of-embed--youtube--vimeo

**Comment by nextgenthemes** [comment]
@henrygd Thanks so much.
