### ISSUE TITLE
Feature request: Option for limiting the maximal width

### ISSUE THREAD

**Issue by nextgenthemes** [henrygd/bigpicture#31]
I tried to use: https://codepen.io/nnico/pen/MWWjqJo
```
#bp_sv {
	width: 96vw !important;
	max-width: 500px !important;
}
```

but is messes things up. Any idea or maybe a option of I limit the maximal width of the lightbox?

**Comment by henrygd** [comment]
It's possible to do this w/ css, but not ideal. I'll try to figure out a solution for setting max width and aspect ratio (#30 ) next release.

https://codepen.io/henrygd/pen/vYYyZZW

**Comment by henrygd** [comment]
Added in 2.3.0. Updated the pen above to work without css hacks.

https://github.com/henrygd/bigpicture#change-dimensions-of-embed--youtube--vimeo
