### ISSUE TITLE
dimensions not working for <video>

### ISSUE THREAD

**Issue by nextgenthemes** [henrygd/bigpicture#42]
See: https://codepen.io/nnico/pen/QWyERbw

I can simply set the dimensions on the created `<video>` in `animationStart` and that seems to work fine. Not sure if that is the best way to do it but I think it should be part of the script.

Because aspect ratio and height work automatically for `<video>` I think only width is needed.

**Comment by henrygd** [comment]
The dimensions are only for iframe elements. So `iframeSrc`, `ytSrc`, and `vimeoSrc`. The readme is a bit of a mess at the moment so I understand the confusion.

For videos, you can use CSS to make them a certain width:

```css
#bp_vid {
  width: 640px;
}
```

Would that solve your use case?

**Comment by nextgenthemes** [comment]
Yes right I could simply use that CSS.

Well there is not really something to "solve". I already solved it for myself in that way but not really liked it.

For my case I want to set it from JS because I have to set it for iframes via dimensions anyway. So I thought for consistency it should work for video as well and along the way I figured its probably best to only set the `style.width` for the `<video>`. So you could take only the width from dimensions and set that on `<video>`s. Also a bit weird maybe, I don't know. Feel free to close.

**Comment by henrygd** [comment]
Went ahead and added this in 2.5.1
