### ISSUE TITLE
Destroy BigPicture

### ISSUE THREAD

**Issue by jantimon** [henrygd/bigpicture#44]
Hey,

thanks for this lightweight simple image modal plugin 👍
Is there any way to close the current open image and remove all memory allocations?

**Comment by henrygd** [comment]
Hi there,

This isn't in the readme yet because I've been lazy about updating it, but as of 2.5.0 you can do this:

```javascript
// assign to a variable
let bp = BigPicture({
	el: e.target,
	imgSrc: 'https://yourimage.jpg',
})

// close
bp.close()
```

It just exposes the normal close function inside BigPicture which clears out the dom and removes any newly created elements.

Does that work for you?

**Comment by jantimon** [comment]
Cool thanks 👍
