### ISSUE TITLE
Feature request. Make use of youtube nocookie domain.

### ISSUE THREAD

**Issue by KumaVolt** [henrygd/bigpicture#46]
YouTube embedded videos set up cookies without user's consent in the browser. This is violation of ePrivacy Regulation. 

Proposal to make an option using of [youtube-nocookie.com](url) domain instead.

**Comment by KumaVolt** [comment]
#47 This pull request implements the youtube-nocookie domain.

**Comment by henrygd** [comment]
Merged, thanks 👍
