### ISSUE TITLE
Content Security Error - refused to evaluate string

### ISSUE THREAD

**Issue by jantimon** [henrygd/bigpicture#48]
Hey @henrygd 

we are testing bigpicture together with [Content Security Policy (CSP)
](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)

Unfortunately CSP refuses to execute this line:

https://github.com/henrygd/bigpicture/blob/68cc9220c971f9f3d745ae6bb5ec8a175561b836/index.js#L656-L657

The reason is that `animationEnd` is `undefined`.  
Would it be possible to wrap this call with an `if` or to set `animationEnd` to a noop function?

<img width="842" alt="secutiry" src="https://user-images.githubusercontent.com/4113649/89764226-4dc73e00-daf4-11ea-98da-55c130ba2874.png">

**Comment by jantimon** [comment]
Thank you so much! 👍

Just one question why do you store the result of setTimout (a number) in a function variable?

**Comment by henrygd** [comment]
No problem. It's just stored so we can stop the function from running if the container is closed before the animation ends.

https://github.com/henrygd/bigpicture/blob/master/src/BigPicture.js#L696
