### ISSUE TITLE
Es6 modules

### ISSUE THREAD

**Issue by cleudson** [henrygd/bigpicture#49]
I think it would be good split de js file into es6 modules. Es6 modules are more easy to test, change and fix. For example, we can create a module that has a function responsible for create elements and than import it into main file.

**Comment by henrygd** [comment]
Makes sense, but I'm not actively developing this library any longer outside of bug fixes or small improvements. If I had new features planned, or we had other regular contributors, I would be all for major refactoring. But for now it's a simple enough script that I have no problem maintaining in its current state.

I am planning to make an improved version from the ground up when I have a bit of time. Hopefully before the end of the year.
