### ISSUE TITLE
Feature request: Option to pass controlslist value to HTML Video

### ISSUE THREAD

**Issue by adarsh4d** [henrygd/bigpicture#51]
It would be best if we have an option that we can pass to the `controllist` of the HTML video tag. The use case for me is to disable the download option `controlslist="nodownload"`.

If the feature already exists, I might have missed it. can you please point it out? 

Thanks for the awesome library.

**Comment by henrygd** [comment]
Have you tried handling this with `animationStart`?

```js
BigPicture({
  animationStart: () => {
    let vid = document.getElementById("bp_vid");
    vid.setAttribute("controlslist", "nodownload");
  }
});
```

Working example using `controlslist="nodownload"`: https://codesandbox.io/s/headless-wildflower-tn67c?file=/index.html

**Comment by adarsh4d** [comment]
Works perfectly! Thank you so much.
