### ISSUE TITLE
Feature request: add swipe support

### ISSUE THREAD

**Issue by redtopia** [henrygd/bigpicture#52]
It would be great to support basic swipe events:

swipe up/down - close
swipe left - next slide
swipe right - previous slide

This is a great library... love the simplicity. Thank you!!!

**Comment by henrygd** [comment]
Left / right swipe should work. What device / browser are you using?

**Comment by redtopia** [comment]
Oh good... I haven't loaded a gallery yet so I wasn't sure. Either an option to swipe up/down to close, or by default, would be the feature request then. Thanks!

**Comment by henrygd** [comment]
Going to leave up / down swipes alone for now as you can tap to close and some may want up / down scrolling while a gallery is open.
