### ISSUE TITLE
Feature request: support pinch zoom in/out

### ISSUE THREAD

**Issue by redtopia** [henrygd/bigpicture#53]
Seems like I should be able to natively pinch zoom in/out when viewing an image on a mobile device when my viewport setting doesn't prevent it, as so:

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

However, when showing an image, I cannot zoom in/out.

**Comment by henrygd** [comment]
I agree that's a bit annoying. I'll look into it soon when I have some time.
