### ISSUE TITLE
Feature request - support for iframes with variable height

### ISSUE THREAD

**Issue by redtopia** [henrygd/bigpicture#55]
I would like to set the height of an iframe to be something other than the aspect ratio calculated from the width/height of the dimension array in the options. Is this possible?

Scenario: I have an iframe embed that renders a media player along with some text, so the height of the embed can vary. I want to use as much of the window as I can to render the iframe.

Here's what I'm doing to accomplish this at the moment (using jquery):

	BigPicture({
		el: $(elem).get(0),
		iframeSrc: 'iframe.html',
		animationStart: function () {
			var wrap = $('#bp_sv'),
				iframe = $('>iframe', wrap);
			$(iframe).on('load', function () {
				var maxHeight = $(window).height() - 50,
					native = $(this).get(0)
					height = Math.min(native.contentWindow.document.body.scrollHeight + 30, maxHeight);
				$(wrap).css({
					height: height + 'px'
				});
			});
		}
	});

A couple issues:

1. Resizing is a problem... even if I add code to resize, I'll be fighting with BP because it's also resizing. Perhaps BP could support a resize callback?
2. It would be better to apply the `load callback` to the iframe immediately when the its created so I don't miss the event
3. I'm accessing #bp_sv directly, which is not documented

I'm guessing the easiest thing to do would be to add a height option for an iframe, like:

    iframeHeight: 'auto' | 'content' | callback

Then, the `auto` option would be the way it works now. The `content` option is more or less the code I have above (I'm sure it could be more robust), and a callback would allow the app to return a height.

**Comment by henrygd** [comment]
Unfortunately I don't think you can access document properties like that on cross-origin frames, which is what most people will be using.

I can make the BigPicture function return the iframe and a function to update the dimensions, though, to make what you're doing a bit easier. For example that would make it possible to do something like this:

```js
let bpInstance = BigPicture({
  el: $(elem).get(0),
  iframeSrc: 'iframe.html'
})

let frame = bpInstance.display.querySelector('iframe')

function resizeFrame() {
  // add resize logic here to calculate w, h
  bpInstance.opts.dimensions = [w, h]
  bpInstance.updateDimensions()
}

frame.addEventListener('load', resizeFrame)
window.addEventListener('resize', () => setTimeout(resizeFrame, 1))
```

You might want to also use the onClose callback and removeEventListener to clean up the listeners afterward but should work in theory.

**Comment by redtopia** [comment]
Thanks... yea there are a few approaches that one could take. I took the liberty to modify the BP source and I got it working nicely by adding a few options. My iframes are local, so I'm not dealing with cross origin issues. I would be happy to share my changes with you, or do a PR... whatever works for you. I did some limited testing and I think my changes don't affect existing functionality, but another set of eyes on it would be great.

**Comment by henrygd** [comment]
I'll take a look if you make a fork, but just fyi the main thing I want to avoid is adding weight to the lib.

I definitely agree this should be easier to do, but I don't necessarily want to add code to solve unusual use cases individually. The changes I suggested above give people more to work with in general for custom implementations while only adding 20-30 bytes. It's a compromise, and I know I'm being a stickler, but I want to keep this thing as light as possible. It would make sense in a more feature rich alternative, which I've wanted to do for years but keeps getting put on the back burner. Maybe soon.

**Comment by redtopia** [comment]
Cool... I'll fork it. Maybe it will give you some ideas at least. When I was digging in, I could tell that you are being super lightweight-minded and I tried to honor that. If anything, maybe my changes will give you some ideas and you'll have a better way of implementing them.

In a nutshell, I gave the caller much more control over sizing the iframe. But I definitely did not look at the number of bytes that I added to the library! :)

**Comment by henrygd** [comment]
You can do a pr, or just fork the repo and link after the changes are pushed. I'm flying out to my brother's wedding tomorrow so I probably won't get around to looking at it until at least after the weekend.

**Comment by henrygd** [comment]
Thanks for the PR, sorry it took so long to get back around to this. I think it's just a bit too much to add given the scope of the library and the unlikeliness of others needing the same functionality, but I did expose the `updateDimensions` function to make this easier in the future.

https://github.com/henrygd/bigpicture#change-dimensions-of-embed--youtube--vimeo
