### ISSUE TITLE
Feature request : control the video looping

### ISSUE THREAD

**Issue by aschoenher** [henrygd/bigpicture#60]
Hello and thank you for your excellent library.

I'm using it on a small portfolio website for an artist and I'd like to disable the video looping.
It's forced to true here : [https://github.com/henrygd/bigpicture/blob/master/src/BigPicture.js#L255](https://github.com/henrygd/bigpicture/blob/master/src/BigPicture.js#L255) could you please consider adding an option to disable this behavior ?

Thanks and have a great day 👍

**Comment by henrygd** [comment]
No worries, I appreciate it. There is currently a loop option, but it's meant for galleries. Maybe it can be repurposed for videos, but in the meantime you should be able to do something like this:

```js
let bp = BigPicture({...})
bp.display.removeAttribute('loop')
```

Let me know if that doesn't work for you. If I push an update to make the loop option work with videos I'll comment here later.

**Comment by aschoenher** [comment]
Thanks for your quick response !

Sadly when I `console.log()` the bp object or bp.display I can see the close, next, prev methods, but bp.display is always undefined. Am I doing something wrong ?

Thanks for your help.

**Comment by henrygd** [comment]
No, probably just a version issue. That property was added in the latest release (2.6.1), so try updating and see if it shows up.

**Comment by aschoenher** [comment]
It works perfectly, thanks for your precious time !

**Comment by aschoenher** [comment]
Sorry for the spam but, is there anyway to support your work ? Do you received small donations or do you have a patreon ? I can't find anything on this repo or on your github page.

**Comment by henrygd** [comment]
No need but I appreciate the kindness. I'm always surprised when people ask this and it's a good motivator to continue open source work, knowing that people find it useful.

I did just sign up for github sponsors as I'll probably be more active this year (approval pending). But again, there's no need to contribute anything. I'm okay financially and would just use it to sponsor someone else :)
