### ISSUE TITLE
HLS Support?

### ISSUE THREAD

**Issue by sjc57** [henrygd/bigpicture#65]
I tried adding vidSrc='......m3u8' but didn't work. Any way to make this work, or plans to add it? Thanks

**Comment by henrygd** [comment]
No plans to add this.

Unless HLS becomes more widely supported you'll need to use an additional library like [hls.js](https://github.com/video-dev/hls.js) or [video.js](https://github.com/videojs/video.js/) to play it.

Here's an example with video.js:

https://stackblitz.com/edit/js-r2cnan?file=index.js

Note that I added an additional rule in `style.css` to fix the control bar.
