### ISSUE TITLE
Implement on plain-Jane, non-framework, basic HTML/JS/CSS pages

### ISSUE THREAD

**Issue by cssyphus** [henrygd/bigpicture#67]
Please provide instructions and code for implementing BigPicture (and BiggerPicture) on plain-Jane, non-framework, no-libraries, simple, basic HTML/JavaScript/CSS page.

I was able to get BigPicture working by copying the minimized BigPicture.js source code (via DevTools) from your demo page and experimenting, but it would be nice to have the unminimized, non-NPM source, and also the implementation code example.

BigPicture is doing the job for me for this simple site, but I would like to try out BiggerPicture as well - however, I am hesitant to go through same again (not that it took all that much time to troubleshoot, but it would be nice to make it a plug-and-play experience)

**Comment by redtopia** [comment]
This is a plain-jane javascript library. The instructions for using it are on the home page of this repo. Download the latest build and follow the instructions in the documentation.

**Comment by henrygd** [comment]
To expand on what JP said, you can find both the minified and unminifed production builds in the [dist ](https://github.com/henrygd/bigpicture/tree/master/dist) folder of this repo, as well as on CDNs like [jsDelivr](https://www.jsdelivr.com/package/npm/bigpicture?path=dist&tab=files). Same with bigger-picture. They are both vanilla javascript libraries.

The bigger-picture [demo site](https://biggerpicture.henrygd.me/) has lots of vanilla js code examples and codesandboxes to play with, so setup can be mostly copy + paste. The [readme](https://github.com/henrygd/bigger-picture/blob/main/readme.md) goes into more detail.

If you run into trouble and have a specific question, let me know.
