### ISSUE TITLE
Provide build for npm 

### ISSUE THREAD

**Issue by reeslo** [henrygd/bigpicture#7]
Please

**Comment by henrygd** [comment]
It's on npm:
https://www.npmjs.com/package/bigpicture

**Comment by reeslo** [comment]
Yep, but dist folder are ignored :/

**Comment by henrygd** [comment]
Sorry, been busy during the holidays.

I can add the dist folder to npm no problem but I'm just curious why you need it. You can still require the package and use the script from index.js, right? Or are you trying to use unpkg or something?

**Comment by JON418** [comment]
Actually, the script from index.js is missing the global.BigPicture declaration so it is unusable as is. Removing `dist` from `.npmignore` would be appreciated, thanks!

**Comment by henrygd** [comment]
Okay, no worries. Added the dist folder on npm so you can use it that way now.
