### ISSUE TITLE
Iframe

### ISSUE THREAD

**Issue by matteocattelan** [henrygd/bigpicture#9]
Hi,
is possible to open an iframe? Or html div?

Thanks you

**Comment by robertjwozniak** [comment]
Hi @matteocattelan,
What do you mean by saying - open an iframe or HTML div?
Do you mean, when you click on the video, it will open an iframe with the video inside of that iframe?

**Comment by matteocattelan** [comment]
I managed to open a html from url, i added a small parameter that create iframe structure but not video content.
